USE ROLE accountadmin;

CREATE DATABASE IF NOT EXISTS DEMO;
CREATE SCHEMA IF NOT EXISTS DEMO.KAIBALAB;

USE SCHEMA DEMO.KAIBALAB;

CREATE OR REPLACE API INTEGRATION GIT_API_INTEGRATION_RAG_GUIDE
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/hwatari-snow')
  ENABLED = TRUE;

CREATE OR REPLACE GIT REPOSITORY DEMO.KAIBALAB.RAG_GUIDE_REPO
  API_INTEGRATION = GIT_API_INTEGRATION_RAG_GUIDE
  ORIGIN = 'https://github.com/hwatari-snow/RAG_guide.git';

ALTER GIT REPOSITORY DEMO.KAIBALAB.RAG_GUIDE_REPO FETCH;

CREATE STAGE IF NOT EXISTS DEMO.KAIBALAB.RAG_PDF
  DIRECTORY = (ENABLE = TRUE);

COPY FILES
  INTO @DEMO.KAIBALAB.RAG_PDF
  FROM @DEMO.KAIBALAB.RAG_GUIDE_REPO/branches/main/pdf/
  PATTERN = '.*[.]pdf';

LS @DEMO.KAIBALAB.RAG_PDF;
